apiVersion: certificates.k8s.io/v1
kind: CertificateSigningRequest
metadata:
  name: victoryhouse-csr
spec:
  groups:
  - system:authenticated
  request: <key>
  signerName: kubernetes.io/kube-apiserver-client
  usages:
  - digital signature
  - key encipherment
  - client auth