apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-log
spec: 
  persistentVolumeReclaimPolicy: Retain
  accessModes:
    - ReadWriteMany
  Capacity:
    storage: 100Mi
  hostPath:
    path: /pv/log

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: claim-log-1
spec: 
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 50Mi

---
apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    name: nginx
spec:
  containers:
  - name: nginx
    image: nginx:alpine
    volumeMounts:
      - name: local-persistent-storage
        mountPath: /var/www/html
  volumes:
    - name: local-persistent-storage
      persistentVolumeClaim:
        claimName: local-pvc

---
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: nginx
  name: nginx
spec:
  containers:
  - image: nginx:alpine
    name: nginx
    volumeMounts:
      - name: local-persistent-storage
        mountPath: /var/www/html
  volumes:
    - name: local-persistent-storage
      persistentVolumeClaim:
        claimName: local-pvc